//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Servi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unit
    {
        public int gkey { get; set; }
        public int unitNbr { get; set; }
        public string lineOp { get; set; }
        public Nullable<int> ibActualVisit { get; set; }
        public Nullable<int> obActualVisit { get; set; }
        public string category { get; set; }
        public string vStat { get; set; }
        public string tState { get; set; }
        public string frghtKind { get; set; }
    
        public virtual Container Container { get; set; }
        public virtual VesselVisit VesselVisit { get; set; }
        public virtual VesselVisit VesselVisit1 { get; set; }
    }
}
