//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContainerMirror
    {
        public int gKey { get; set; }
        public string equipmentNbr { get; set; }
        public string typeIso { get; set; }
        public string owner { get; set; }
        public decimal typeLength { get; set; }
        public Nullable<decimal> tareWt { get; set; }
        public Nullable<decimal> safewt { get; set; }
    }
}
