//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Drawing.Printing;
using Microsoft.Ajax.Utilities;

namespace MVCBase
{
    using System;
    using System.Collections.Generic;

   
    public partial class VesselVisit
    {

        public int id { get; set; }
        public string visit { get; set; }
        public string line { get; set; }
        public string vesselName { get; set; }
        public string phase { get; set; }
        public Nullable<System.DateTime> ata { get; set; }
        public Nullable<System.DateTime> atd { get; set; }
        public Nullable<System.DateTime> eta { get; set; }
        public Nullable<System.DateTime> etd { get; set; }
        public string serv { get; set; }
    }

    
}
